# Generated by Django 3.2.5 on 2021-07-09 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210707_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(400000), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
