# Generated by Django 3.2.5 on 2021-07-22 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210715_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('status', models.CharField(choices=[('active', 'active'), ('dead', 'dead')], default='active', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='car_default.jpeg', upload_to=''),
        ),
    ]
