# Generated by Django 3.2.5 on 2021-07-22 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210722_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
