# Generated by Django 3.2.5 on 2021-07-22 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='sale',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
